function named_material(name)
    for _, x in pairs(materials) do
        if x.name == name then
            return x
        end
    end
end

function extract_tier(something)
    if type(something) == "number" then
        return something
    end

    if type(something) == "table" and something.tier then
        return something.tier
    end

    if type(something) == "string" then
        for i = 0, 7 do
            if string.find(something, tier_material[i + 1]) then
                return i
            end
        end
    end

    return 0
end

materials = {
    {
        name = "Hand",
        label = "Hand",
        craftable = false,
        is_exact = true,
    },
    {
        name = "NoMaterial",
        label = "NoMaterial",
        craftable = false,
    },
    {
        name = "Computations",
        label = "Computations",
        is_abstract = true,
        description = {{"calculations", "common"}},
    },
    {
        name = "Heat",
        label = "Heat",
        is_abstract = true,
        -- unit = "J",
        unit_s = "W",
        unit_mul = 1,
    },
    {
        name = "Electricity",
        label = "Electricity",
        is_abstract = true,
        -- unit = "J",
        unit_s = "W",
        unit_mul = 1,
    },
    {
        name = "Kinetic",
        label = "Kinetic",
        is_abstract = true,
        -- unit = "J",
        unit_s = "W",
        unit_mul = 1,
    },
    {
        name = "Copper",
        label = "Copper",
        is_ingot = true,
        is_dust = true,
        smelt_level = 0,
        is_block = true,
    },
    {
        name = "Gold",
        label = "Gold",
        is_dust = true,
        is_ingot = true,
        smelt_level = 0,
        is_block = true,
    },
    {
        name = "Superconductor",
        label = "Superconductor",
        is_dust = true,
        is_ingot = true,
        smelt_level = 4,
        is_block = true,
    },
    {
        name = "Iron",
        label = "Iron",
        is_dust = true,
        is_ingot = true,
        smelt_level = 0,
        is_block = true,
    },
    {
        name = "CircuitBoard",
        label = "Circuit Board",
        is_exact = true,
        mesh = "Models/BoardCrate",
        materials = {"Materials/Plastic"},
    },
    {
        name = "AdvancedCircuitBoard",
        label = "Advanced Circuit Board",
        is_exact = true,
        mesh = "Models/BoardCrate",
        materials = {"Materials/DarkGreenPlastic"},
    },
    {
        name = "Plastic",
        label = "Plastic",
        is_exact = true,
    },
    {
        name = "Steel",
        label = "Steel",
        is_ingot = true,
        is_dust = true,
        smelt_level = 1,
        is_block = true,
    },
    {
        name = "Aluminium",
        label = "Aluminium",
        is_dust = true,
        is_ingot = true,
        smelt_level = 3,
        is_block = true,
    },
    {
        name = "AluminiumOxide",
        label = "Aluminium Oxide",
        is_dust = true,
        smelt_level = 3,
        is_block = true,
    },
    {
        name = "StainlessSteel",
        label = "Stainless Steel",
        smelt_level = 3,
        is_ingot = true,
        is_dust = true,
        is_block = true,
    },
    {
        name = "Titanium",
        label = "Titanium",
        smelt_level = 4,
        is_ingot = true,
        is_dust = true,
        is_block = true,
    },
    {
        name = "TitaniumTetrachloride",
        label = "Titanium Tetrachloride",
        smelt_level = 4,
        is_fluid = true,
    },
    {
        name = "TitaniumSponge",
        label = "Titanium Sponge",
        smelt_level = 4,
        is_exact = true,
    },
    {
        name = "TitaniumOxide",
        label = "Titanium Oxide",
        is_dust = true,
    },
    {
        name = "PreparedTitaniumOxide",
        label = "Prepared Titanium Oxide",
        is_dust = true,
    },
    {
        name = "Zink",
        label = "Zink",
        smelt_level = 0,
        is_metal = true,
        is_dust = true,
        is_block = true,
    },
    {
        name = "Lithium",
        label = "Lithium",
        smelt_level = 0,
        is_metal = true,
        is_dust = true,
        burnable = {burn_time = 18 * 20, heat_per_tick = 18, total_ash = 0.06},
        is_block = true,
    },
    {
        name = "Tungsten",
        label = "Tungsten",
        smelt_level = 4,
        is_dust = true,
        tier = 5,
    },
    {
        name = "TungstenOxide",
        label = "Tungsten Oxide",
        smelt_level = 4,
        is_dust = true,
        tier = 5,
    },
    {
        name = "TungstenCarbide",
        label = "Tungsten Carbide",
        is_dust = true,
        tier = 5,
    },
    {
        name = "HardMetal",
        label = "Hard Metal",
        smelt_level = 4,
        is_ingot = true,
        is_dust = true,
        tier = 5,
        is_block = true,
    },
    {
        name = "HotHardMetalIngot",
        label = "Hot Hard Metal Ingot",
        smelt_level = 4,
        is_exact = true,
        tier = 5,
        mesh = "Models/Ingot",
        materials = {"Materials/HotMetal"},
    },
    {
        name = "HotNeutroniumIngot",
        label = "Hot Neutronium Ingot",
        smelt_level = 4,
        is_exact = true,
        tier = 5,
        mesh = "Models/Ingot",
        materials = {"Materials/VeryHotMetal"},
    }
    -- ,{
    -- 	name = "Rubber",
    -- 	label = "Rubber",
    -- 	smelt_level = 0,
    -- 	is_metal = true,
    -- 	is_dust = true,
    -- 	tier = 2
    -- }
    ,
    {
        name = "Cobalt",
        label = "Cobalt",
        smelt_level = 4,
        is_dust = true,
        tier = 5,
        is_block = true,
    },
    {name = "CobaltOxide", label = "Cobalt Oxide", is_dust = true, tier = 5},
    {
        name = "Stone",
        label = "Stone",
        tier = 0,
    },
    -- },{
    -- 	name = "Bronze",
    -- 	label = "Bronze",
    -- 	smelt_level = 2,
    -- 	is_metal = true,
    -- 	is_dust = true,
    --
    -- 	is_block = true
    -- },{
    -- 	name = "Brass",
    -- 	label = "Brass",
    -- 	smelt_level = 2,
    -- 	is_metal = true,
    -- 	is_dust = true,
    --
    -- 	is_block = true
    -- },{
    -- 	name = "BrassDetails",
    -- 	label = "Brass Parts",
    --
    -- 	is_exact = true,
    -- 	category = "Component"
    -- },{
    -- 	name = "BrassReductor",
    -- 	label = "Brass Reductor",
    --
    -- 	is_exact = true,
    -- 	category = "Component"
    -- },
    {
        name = "Cement",
        label = "Cement",
        is_dust = true,
    },
    {
        name = "Neutronium",
        label = "Neutronium",
        is_ingot = true,
        is_dust = true,
        tier = 6,
    },
    {
        name = "Chromium",
        label = "Chromium",
        smelt_level = 0,
        is_dust = true,
        tier = 3,
    },
    {
        name = "Plutonium",
        label = "Plutonium",
        is_block = true,
        is_dust = true,
    },
    {
        name = "Uranium",
        label = "Uranium-238",
        is_block = true,
        is_dust = true,
    },
    {
        name = "Uranium235",
        label = "Uranium-235",
        is_block = true,
        is_dust = true,
    },
    {
        name = "Uranium233",
        label = "Uranium-233",
        is_block = true,
        is_dust = true,
    },
    {
        name = "Uranium233Cell",
        label = "Uranium 233 Cell",
        tier = 5,
        is_exact = true,
        stack = 32,
        description = {{"NuclearFuel", "common"}},
    },
    {
        name = "UraniumCell",
        label = "Uranium Cell",
        tier = 5,
        is_exact = true,
        stack = 32,
        description = {{"NuclearFuel", "common"}},
    },
    {
        name = "PlutoniumCell",
        label = "Plutonium Cell",
        tier = 5,
        is_exact = true,
        stack = 32,
        description = {{"NuclearFuel", "common"}},
    },
    {
        name = "DepletedUraniumCell",
        label = "Depleted Uranium Cell",
        tier = 5,
        is_exact = true,
        stack = 32,
        description = {{"NuclearFuel", "common"}},
    },
    {
        name = "Thorium",
        label = "Thorium",
        is_block = true,
        is_dust = true,
    },
    {
        name = "Sodium",
        label = "Sodium",
        is_dust = true,
        tier = 3,
        is_block = true,
    },
    {
        name = "Potassium",
        label = "Potassium",
        is_dust = true,
        tier = 3,
        is_block = true,
    },
    {
        name = "Sulfur",
        label = "Sulfur",
        is_exact = true,
        mesh = "Models/Dust",
    },
    {
        name = "Steam",
        label = "Steam",
        is_gas = true,
        -- unit = "J",
        unit_mul = 1,
        color = {1, 1, 1},
    },
    {
        name = "Chlorine",
        label = "Chlorine",
        is_gas = true,
        tier = 4,
        color = {1, 1, 0},
    },
    {
        name = "Peat",
        label = "Peat",
        is_exact = true,
        burnable = {burn_time = 400, heat_per_tick = 10, total_ash = 0.24},
        tier = 0,
        color = {0.2, 0.2, 0.0},
        mesh = "Models/Piece",
    },
    {
        name = "Coal",
        label = "Coal",
        is_exact = true,
        burnable = {burn_time = 400, heat_per_tick = 20, total_ash = 0.12},
        tier = 0,
        color = {0.0, 0.0, 0.0},
        mesh = "Models/Piece",
    },
    {
        name = "Coke",
        label = "Coke",
        is_exact = true,
        burnable = {burn_time = 400 / 1.5, heat_per_tick = 30 * 1.5, total_ash = 0.06},
        color = {0.0, 0.0, 0.0},
        mesh = "Models/Piece",
    },
    {
        name = "Creosote",
        label = "Creosote",
        is_gas = true,
        burnable = {
            burn_time = 400,
            heat_per_tick = 20,
        },
        tier = 0,
        color = {0.0, 0.0, 0.0},
        mesh = "Models/Piece",
    },
    {
        name = "ProducerGas",
        label = "Producer Gas",
        is_gas = true,
        burnable = {burn_time = 400, heat_per_tick = 80, total_ash = 0},
        color = {1, 1, 1},
    },
    {
        name = "CarbonMonoxide",
        label = "Carbon Monoxide",
        is_gas = true,
        burnable = {burn_time = 200, heat_per_tick = 40, total_ash = 0},
        color = {1, 1, 1},
    },
    {name = "Ash", label = "Ash", is_dust = true, tier = 0},
    {
        name = "Hydrogen",
        label = "Hydrogen",
        is_gas = true,
        burnable = {burn_time = 400, heat_per_tick = 160, total_ash = 0},
        tier = 2,
        color = {0.2, 0.2, 0.5},
    },
    {
        name = "Methane",
        label = "Methane",
        is_gas = true,
        burnable = {burn_time = 400, heat_per_tick = 40, total_ash = 0},
        tier = 2,
        color = {0.5, 0.2, 0.2},
    },
    {
        name = "Ethylene",
        label = "Ethylene",
        is_gas = true,
        burnable = {burn_time = 400, heat_per_tick = 50, total_ash = 0},
        tier = 2,
        color = {0.2, 0.5, 0.2},
    },
    -- ,{
    -- 	name = "Nickel",
    -- 	label = "Nickel",
    -- 	smelt_level = 0,
    -- 	is_metal = true,
    -- 	is_dust = true,
    -- 	"IsLiquidMetal": true,
    -- 	is_block = true,
    -- 	tier = 3
    -- }
    {name = "Water", label = "Water", is_fluid = true, tier = 0},
    {
        name = "Glass",
        label = "Glass",
        is_exact = true,
        tier = 0,
    },
    {
        name = "Lense",
        label = "Lense",
        is_exact = true,
        tier = 0,
    },
    {
        name = "Organics",
        label = "Organics",
        is_exact = true,
        tier = 0,
        mesh = "Models/Piece",
        description = {{"Organics", "common"}},
    },
    {
        name = "Biomass",
        label = "Biomass",
        is_fluid = true,
    },
    {
        name = "Clay",
        label = "Clay",
        tier = 0,
        is_exact = true,
        mesh = "Models/Piece",
    },
    {
        name = "OreWater",
        label = "Ore Water",
        is_fluid = true,
    },
    {
        name = "RareEarthElement",
        label = "Rare Earth Element",
        is_exact = true,
        mesh = "Models/Dust",
    },
    {
        name = "Log",
        label = "Log",
        is_exact = true,
        tier = 0,
        burnable = {burn_time = 400, heat_per_tick = 10, total_ash = 0.24},  -- 5.5kwh
        color = {0.9, 0.9, 0.9},
    },
    {
        name = "StoneLog",
        label = "Stone Log",
        is_exact = true,
        tier = 0,
        burnable = {burn_time = 800, heat_per_tick = 10, total_ash = 0.5},
    },
    {
        name = "Plank",
        label = "Plank",
        is_exact = true,
        tier = 0,
        burnable = {burn_time = 100, heat_per_tick = 10, total_ash = 0.24},
    },
    {name = "Silicon", label = "Silicon", is_exact = true, tier = 3},
    {name = "SiliconWafer", label = "Silicon Wafer", is_exact = true, tier = 4},
    {name = "SulfuricAcid", label = "Sulfuric Acid", is_fluid = true, tier = 3},
    {
        name = "RawOil",
        label = "Raw Oil",
        is_fluid = true,
        tier = 0,
        burnable = {burn_time = 400, heat_per_tick = 10, total_ash = 0},
        color = {0.1, 0.1, 0.1},
    },
    {name = "MineralWater", label = "Mineral Water", is_fluid = true, tier = 0},
    {
        name = "Gasoline",
        label = "Gasoline",
        is_gas = true,
        tier = 1,
        burnable = {burn_time = 400, heat_per_tick = 40, total_ash = 0},
        color = {0.5, 0.5, 0.2},
    },
    {
        name = "HeavyOil",
        label = "Heavy Oil",
        is_gas = true,
        tier = 2,
        burnable = {burn_time = 400, heat_per_tick = 20, total_ash = 0},
        color = {0.2, 0.5, 0.2},
    },
    {name = "Battery", label = "Battery", is_exact = true, tier = 3},
    {name = "SiliconOxide", label = "Silicon Oxide", is_exact = true, tier = 1},
    {name = "Pumpkin", label = "Pumpkin", is_exact = true, tier = 0},
    {name = "Oxygen", label = "Oxygen", is_gas = true, tier = 4},
    {name = "Nitrogen", label = "Nitrogen", is_gas = true, tier = 4},
    {name = "ChromiumOxide", label = "Chromium Oxide", is_dust = true, tier = 3},
    {
        name = "PotassiumChloride",
        label = "Potassium Chloride",
        is_dust = true,
        tier = 3,
    },
    {name = "Beryllium", label = "Beryllium", is_dust = true, tier = 4},
    {name = "Yttrium", label = "Yttrium", is_dust = true, tier = 3},
    {name = "Helium", label = "Helium", is_gas = true, is_plasma = true, tier = 4},
    {name = "Salt", label = "Salt", is_dust = true, tier = 4},
    {name = "PortalBase", label = "Portal Base", is_exact = true, tier = 2},
    {name = "Signal", label = "Signal", is_exact = true},
    {
        name = "CopperWire",
        label = "Copper Wire",
        stack = 64,
        is_exact = true,
        category = "Parts",
        mesh = "Models/WireCrate",
        materials = {"Materials/CopperWiresOnCrate"},
    },
    {
        name = "GoldWire",
        label = "Gold Wire",
        stack = 64,
        is_exact = true,
        category = "Parts",
        mesh = "Models/WireCrate",
        materials = {"Materials/GoldWiresOnCrate"},
    },
    {
        name = "SuperconductorWire",
        label = "Superconductor Wire",
        stack = 64,
        is_exact = true,
        category = "Parts",
        mesh = "Models/WireCrate",
        materials = {"Materials/SuperWiresOnCrate"},
    },
    {
        name = "Circuit",
        label = "Circuit",
        stack = 32,
        is_exact = true,
        category = "Parts",
        description = {{"Circuit", "common"}},
        mesh = "Models/CircuitCrate",
    },
    {
        name = "AdvancedCircuit",
        label = "Advanced Circuit",
        stack = 32,
        is_exact = true,
        category = "Parts",
        description = {{"Circuit", "common"}},
        mesh = "Models/Circuit2Crate",
    },
    {
        name = "Processor",
        label = "Processor",
        stack = 32,
        is_exact = true,
        category = "Parts",
        description = {{"Circuit", "common"}},
        mesh = "Models/Circuit3Crate",
    },
    {
        name = "QuantumCircuit",
        label = "Quantum Circuit",
        stack = 32,
        is_exact = true,
        category = "Parts",
        description = {{"Circuit", "common"}},
        mesh = "Models/Circuit3Crate",
    },
    {
        name = "QuantumProcessor",
        label = "Quantum Processor",
        stack = 32,
        is_exact = true,
        category = "Parts",
        description = {{"Circuit", "common"}},
        mesh = "Models/Circuit3Crate",
    },
    {
        name = "QuantumCore",
        label = "Quantum Core",
        stack = 32,
        is_exact = true,
        category = "Parts",
        mesh = "Models/Circuit3Crate",
    },
    {
        name = "QuantumBrain",
        label = "Quantum Brain",
        stack = 32,
        is_exact = true,
        category = "Parts",
        description = {{"Circuit", "common"}},
        mesh = "Models/Circuit3Crate",
    },
    {
        name = "Cell",
        label = "Cell",
        stack = 32,
        is_exact = true,
        category = "Parts",
    },
    {
        name = "Catalyst",
        label = "Catalyst Cell",
        stack = 32,
        is_exact = true,
    },
    {
        name = "UltimateCatalyst",
        label = "Ultimate Catalyst Cell",
        stack = 32,
        is_exact = true,
    },
    {
        name = "MothershipPing",
        label = "Mothership Ping",
        stack = 32,
        is_exact = true,
    },
    {
        name = "ControlCell",
        label = "Control Cell",
        stack = 32,
        is_exact = true,
    },
    {
        name = "ReflectorCell",
        label = "Reflector Cell",
        stack = 32,
        is_exact = true,
    },
    {
        name = "ThoriumCell",
        label = "Thorium Cell",
        stack = 32,
        is_exact = true,
    },
    {
        name = "MixedOxideCell",
        label = "Mixed-Oxide Cell",
        stack = 32,
        is_exact = true,
    },
    {
        name = "RutileCrystal",
        label = "Rutile Crystal",
        stack = 32,
        is_exact = true,
        category = "Mineral",
    },
    {
        name = "UraniniteCrystal",
        label = "Uraninite Crystal",
        stack = 32,
        is_exact = true,
        category = "Mineral",
    },
    {
        name = "UraniniteCluster",
        label = "Uraninite Cluster",
        stack = 32,
        is_exact = true,
        category = "Mineral",
    },
    {
        name = "Cinnabar",
        label = "Cinnabar",
        stack = 32,
        is_dust = true,
        category = "Mineral",
    },
    {
        name = "CinnabarCrystal",
        label = "Cinnabar Crystal",
        stack = 32,
        is_exact = true,
        category = "Mineral",
    },
    {
        name = "CinnabarCluster",
        label = "Cinnabar Cluster",
        stack = 32,
        is_exact = true,
        category = "Mineral",
    },
    {
        name = "Malachite",
        label = "Malachite",
        stack = 32,
        is_dust = true,
        category = "Mineral",
    },
    {
        name = "MalachiteCrystal",
        label = "Malachite Crystal",
        stack = 32,
        is_exact = true,
        category = "Mineral",
    },
    {
        name = "MalachiteCluster",
        label = "Malachite Cluster",
        stack = 32,
        is_exact = true,
        category = "Mineral",
    },
    {
        name = "Mercury",
        label = "Mercury",
        is_fluid = true,
    },
    {
        name = "FilteringCell",
        label = "Filtering Cell",
        stack = 32,
        is_exact = true,
    },
    {name = "Boron", label = "Boron", is_dust = true, tier = 4},
    {
        name = "Borax",
        label = "Borax",
        stack = 32,
        is_dust = true,
        category = "Mineral",
    },
    {
        name = "Emerald",
        label = "Emerald",
        stack = 32,
        is_exact = true,
        is_dust = true,
        category = "Mineral",
    },
    {
        name = "Capacity",
        label = "Capacity",
        craftable = false,
        is_exact = true,
        category = "Signal",
    },
    {
        name = "InputError",
        label = "Input Error",
        craftable = false,
        is_exact = true,
        category = "Signal",
    },
    {
        name = "OutputError",
        label = "Output Error",
        craftable = false,
        is_exact = true,
        category = "Signal",
    },
    {
        name = "Progress",
        label = "Progress",
        craftable = false,
        is_exact = true,
        category = "Signal",
    },
    {
        name = "SwitchedOn",
        label = "Switched On",
        craftable = false,
        is_exact = true,
        category = "Signal",
    },
}