simple_blocks = {
    {name = "WoodenPlanks", label = "Wooden Planks", tier = 0},
    {name = "AdminBlocks", label = "Admin Blocks", tier = 0},
    {name = "StoneTiles", label = "Stone Tiles", tier = 0},
    {name = "RedTiles", label = "Red Tiles", tier = 0},
    {name = "DarkTiles", label = "Dark Tiles", tier = 0},
    {name = "Terracotta", label = "Terracotta", tier = 0},
    {name = "TerracottaTiles", label = "Terracotta Tiles", tier = 0},
    {name = "Bricks", label = "Bricks", tier = 0},
    {name = "RedBricks", label = "Red Bricks", tier = 0},
    {name = "DarkBricks", label = "Black Bricks", tier = 0},
    {name = "TerracottaBricks", label = "Terracotta Bricks", tier = 0},
    {name = "Concrete", label = "Concrete", tier = 2},
    {name = "ConcreteBricks", label = "Concrete Bricks", tier = 2},
    {name = "ConcreteTiles", label = "Concrete Tiles", tier = 2},
    {name = "ConcreteSmallTiles", label = "Concrete Small Tiles", tier = 2},
    {name = "ReinforcedConcrete", label = "Reinforced Concrete", tier = 2},
    {
        name = "ReinforcedConcreteTiles",
        label = "Reinforced Concrete Tiles",
        tier = 2,
    },
    {
        name = "ReinforcedConcreteSmallTiles",
        label = "Reinforced Concrete Small Tiles",
        tier = 2,
    },
    {
        name = "ReinforcedConcreteBricks",
        label = "Reinforced Concrete Bricks",
        tier = 2,
    },
    {name = "DangerBlock", label = "Danger Block", tier = 2},
    {name = "RustyCopperCasing", label = "Rusty Copper Casing", tier = 1},
    {name = "RustyIronCasing", label = "Rusty Iron Casing", tier = 2},
    {name = "BasicPlatform", label = "Basic Platform", tier = 0},
    {name = "PlasticBlock", label = "Plastic Block", tier = 0},
    {name = "GlassBlock", label = "Glass Block", tier = 0},
    {name = "PaintWhite", label = "Paint White", tier = 0},
    {name = "PaintGray", label = "Paint Gray", tier = 0},
    {name = "PaintBlack", label = "Paint Black", tier = 0},
    {name = "PaintGreen", label = "Paint Green", tier = 0},
    {name = "PaintRed", label = "Paint Red", tier = 0},
    {name = "PaintBlue", label = "Paint Blue", tier = 0},
    {name = "PaintCopper", label = "Paint Copper", tier = 0},
    {name = "PaintSteel", label = "Paint Steel", tier = 0},
    {name = "PaintStainlessSteel", label = "Paint StainlessSteel", tier = 0},
    {name = "PaintTitanium", label = "Paint Titanium", tier = 0},
    {name = "PaintHardMetal", label = "Paint Hard Metal", tier = 0},
    {name = "PaintGold", label = "Paint Gold", tier = 0},
    {name = "PaintYellow", label = "Paint Yellow", tier = 0},
    {name = "PaintMagenta", label = "Paint Magenta", tier = 0},
    {name = "PaintCyan", label = "Paint Cyan", tier = 0},
}